### ISSUE TITLE
Support for NAV2018 AL version

### ISSUE THREAD

**Issue by jfuentesdynamizatic** [DanielNT/ALTranslationCenter#11]
Hello @DanielNT,
we still have some clients in **NAV2018** version but with AL code.

We have tried to use your extension applying the following setting:

```json
    "alTranslationCenter.general.customLanguageMapping": {
        "ESP": "es-ES|es-ES_tradnl"
    }
```

However, the action of your extension does nothing... it does not even show any message... as if it were not able to correctly identify the strings from which it should extract the translations from the base .g.xlf file

I'll give you an extract of the content of the .g.xlf file in case it helps you solve the problem:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en-US" original="MyExtension">
    <body>
      <group id="body">
        <trans-unit id="Codeunit 3833440677 - NamedType 3114637384" maxWidth="999" size-unit="char" translate="yes" xml:space="preserve">
          <source>Deleting a registered document it is not allowed.</source>
          <note from="Developer" annotates="general" priority="2">ESP="No está permitido eliminar un documento registrado"</note>
          <note from="Xliff Generator" annotates="general" priority="3">Codeunit - Label</note>
        </trans-unit>
      </group>
    </body>
  </file>
</xliff>
```

**Comment by DanielNT** [comment]
Hi @jfuentesdynamizatic, what version of ```AL Language extension``` are you using? If you are using the ```ALLanguage.vsix``` of NAV2018 it's a known issue of compatibility (if it is lower than version _v4.0.182565_). 

Are all commands failing? Including ```ATC: Generate Xliff Translations from source```?

Thanks.

**Comment by jfuentesdynamizatic** [comment]
Hi @DanielNT ,
to work with this legacy projects, we use the .vsix file downloaded from our NAV2018-latest Dockers environment...

I provide you a screenshot:

![image](https://github.com/DanielNT/ALTranslationCenter/assets/132342443/96c8f6c7-4d41-441f-9ed6-7c34f1603c00)

**Comment by DanielNT** [comment]
Thanks, I will take a look.

**Comment by DanielNT** [comment]
The problem is that `ATC: Package with translation` or `ATC: Publish with translation` cannot be executed in this version, because AL Extension exports are not working, but I fixed `ATC:Generate Xliff translations from source` in version v2.5.1, so you can test it.

**Comment by jfuentesdynamizatic** [comment]
Hi @DanielNT ,
thank you very much... `ATC:Generate Xliff translations from source` works now with latest NAV2018 AL compiler version!
