### ISSUE TITLE
Change only labels with Comments

### ISSUE THREAD

**Issue by DiegoGCarcelen** [DanielNT/ALTranslationCenter#12]
Hello,

Sorry, I know this is not a problem but a feature that I think could be very useful.
It would be possible that there was a command so that the resulting XLF file only fills in the objects that have comments and leave the rest as is?.
I have some translations in the XML file (that are not in the comments) and they are being deleted after running the command.
Is it possible?.

**Comment by DanielNT** [comment]
Hola @DiegoGCarcelen:

Voy a dar una vuelta a lo que comentas. No es la situación ideal pues implica el "mantenimiento" y análisis de los ficheros de traducción (que pueden ser incorrectos), es preferible tenerlo todo en comments, pero entiendo el caso de uso.

**Comment by DanielNT** [comment]
Prueba esta versión y coméntame si te funciona:

Tienes que habilitar en el espacio de trabajo la opción "**Update Xliff Translation Files If Exists**".

[al-translation-center-2.5.4.zip](https://github.com/DanielNT/ALTranslationCenter/files/14394071/al-translation-center-2.5.4.zip)

**Comment by DiegoGCarcelen** [comment]
Hola Daniel,

De momento lo que he probado funciona perfectamente, muchas gracias por tomarte el tiempo de implementar esta característica, te lo agradezco mucho porque me ahorra bastante tiempo. Si encuentro algún error o problema te lo haré saber.

Un saludo y gracias.

**Comment by wansinby** [comment]
Works great. Thank you for the idea and the result.
