### ISSUE TITLE
Generated Files have "wrong" filename with ".g"

### ISSUE THREAD

**Issue by wansinby** [DanielNT/ALTranslationCenter#13]
Dear Daniel,
the xlf-Files ATC generates have the filename "appname.es-ES.g.xlf", but most other programs and also Microsoft recommends "appname.es-ES.xlf", without ".g".
(OK, also appname.es-ES.g.xlf works, and there is no explicit rule about the filename).
In https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files at "The XLIFF file" at the notebox MS recommends <extensionname>.<language>.xlf.

Your naming causes problems in old projects with the MS-filenaming, because after the usage of ATC you now have 2 language files, 1 with .g and 1 without .g. I found this issue when I tested your new setting "Update Xliff Translation Files If Exists".

But if you now change the filename from "with.g" to "without.g", then all projects we already used ATC get 2 languagefiles.

Maybe an idea is a setting for the filename (with or without .g) - or maybe you have a great idea how to handle this problem.

Best regards, Wolfram

**Comment by DanielNT** [comment]
Hi @wansinby,

That's a good point. I'll check it out.

**Comment by DanielNT** [comment]
I've published yesterday the version v2.6.2, with a new option for changing the format.

**Comment by wansinby** [comment]
Dear Daniel, I have seen it before I got your email. Thank you very much, in a short test it works fine. So issue can be closed.
