### ISSUE TITLE
Tooltips on table field level are not displayed correctly 

### ISSUE THREAD

**Issue by jthoerner-tso** [DanielNT/ALTranslationCenter#15]
Hi, small issue.
If you add a tooltip with translation to a table field in BC24, this translation is currently not displayed in the UI, i.e. on the page. 

I have found out that the problem is caused by the attribute ‘original’, which contains the file name of the .g.xlf.

Currently this line is generated like this.
`<file datatype="xml" source-language="en-US" target-language="de-CH" original="General">`

However, it only works if the line is set up like this:
`<file datatype="xml" source-language="en-US" target-language="de-CH" original="General.g.xlf">`

The other translations still work as expected. Maybe this is also a bug in my BC24 version..

**Comment by DanielNT** [comment]
Hi @jthoerner-tso, thanks for reporting the issue.

I think that your issue may be related to your VS Code extension for translation (I suppose that is _AL Translation Center_), not _AL Translation Snippets_ itself.

I created a new project, using **AL Language extension for Microsoft Dynamics 365 Business Central v14.0.1108692** (pre-release), and last version of **AL Translation Center (v2.6.2)** with a table with one field that have a table tooltip.

The result was OK, as stated by the picture below, without the need of add "g.xlf":

![image](https://github.com/user-attachments/assets/4427e787-5c7c-44ae-8606-1044fec6d1c8)

I attach my test project below. Feel free to modify to replicate the issue.
[General.zip](https://github.com/user-attachments/files/16716059/General.zip)

I suspected at first that the name "General" could be source of the issue (after seeing your modification), but at the moment, as I say, I need more information.
![image](https://github.com/user-attachments/assets/e8ab61ef-31db-4103-aeae-620d2c64ca29)

**Comment by jthoerner-tso** [comment]
Hi Daniel, 
yes, this topic actually belongs to the _AL Translation Center_ .

Thank you for the project. I tested your demo project with the latest version of AL Translation Centre in a BC24.4 environment, and it works as expected even without “g.xlf”.

Thank you for the project. I have tested your demo project with the latest version of AL Translation Center in a BC24.4 environment, and it works as you say, even without “g.xlf”.

Interestingly, for fields that are created via table extension, the tooltips do not seem to work without the addition of “g.xlf”.

![image](https://github.com/user-attachments/assets/7240a0fa-2201-4290-9e4f-8f57337f7b97)


I have extended your project to reflect this behavior. Please also feel free to try out the extended project. 
[General2.zip](https://github.com/user-attachments/files/16744880/General2.zip)

**Comment by DanielNT** [comment]
I'm going to transfer the issue to the right repository, for keeping a eye on it. 

Maybe an AL Extension bug? https://github.com/microsoft/AL/issues/7790#issuecomment-2221533430

**Comment by DanielNT** [comment]
As stated in https://github.com/microsoft/AL/issues/7790#issuecomment-2339489928 is technically fixed at server side for BC24/25, and probably the logic of object extensions will be modified in the future. 

I am going to close the issue for now. Thanks for your feedback.
