### ISSUE TITLE
There was an error reading the app.json file

### ISSUE THREAD

**Issue by plc5700** [DanielNT/ALTranslationCenter#3]
Hi

When I develop AL code using my VSCode for App everything works perfectly, except for ALTranslationCenter.

Whenever I invoce a ATC command from the Command Palette - i get the error in the subject.
If I commit the project tot git and clone it onto a Windows with VSCode - the project works just fine without modifications.

After invoking the commands on windows, and commit and clone back to my mac, I still get the same error if I try to invoke ATC commands.

I don't know where I can find any further details about the issue.

This is the details about my Mac VSCode:
```
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T17:07:18.579Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
```
This is the information about my windows VSCode:
```
Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No
```

I'm using ALTranslation Center v. 1.3.3 on both platforms.

**Comment by DanielNT** [comment]
Hello @plc5700, do you have the same problem with a basic "AL: Go!" project (with translations enabled)? Maybe is a problem at getting the path of the file in Mac. I will investigate this.

**EDIT**: It's a path separator problem, it's not the same as Windows. I'll fix this ASAP.

**Comment by DanielNT** [comment]
Version **1.3.4** is now in VS Marketplace. Could you try it @plc5700?

**Comment by DanielNT** [comment]
I'm going to close the issue, as I tested it in MacOS and it works. If you detect any problem, I'll reopen the issue. Thanks.
