### ISSUE TITLE
file es-ES.g.xlf and file es-ES.g.tradnl.g.xlf

### ISSUE THREAD

**Issue by mpachecodynamizatic** [DanielNT/ALTranslationCenter#4]
Hello

Would it be possible that just putting Caption = 'Vendor No.', Comment = 'ESP="Vendor No."'; 2 translation files would be generated.

en-ES.g.xlf
en-ES.g.tradnl.g.xlf

I have tried in the configuration to put 2 lines for ESP but it is not possible.

Thank you.

**Comment by DanielNT** [comment]
Hi @mpachecodynamizatic:

The feature that you describe is not supported at this time, but this could be an interesting addition.

I will work on it and try to update the extension.

**Comment by DanielNT** [comment]
Version is updated at marketplace. Can you try it?

![Example of use](https://i.ibb.co/Hn1bSv0/custom-Language-Mapping-Multi.png)

**Comment by mpachecodynamizatic** [comment]
Ok, it works properly. 
Thank you very much.

**Comment by DanielNT** [comment]
Thanks for the feedback.
