### ISSUE TITLE
Error with special characters like ()[]<>|*

### ISSUE THREAD

**Issue by wansinby** [DanielNT/ALTranslationCenter#6]
Dear Daniel,
I've been using "AL Language Tool" a long time and now I found your great imporvement and bug-fixing, tnx for this.
Your tool found a lot of wrong translations in our code, so I was able to fix this. But ALTranslationCenter throws an error if the translation has special characters. Please, can you fix this? After generating all translations I check the XLIFF-files with "XLIFF: check for missing translations" of the extension "XLIFF Sync", so I have to translate ALL labels ...

Here are the Labels causing the "Translation error":
OptionTemplateLbl: Label '<Field name="%1">%2</Field>', Comment = 'DEU="<Field name="%1">%2</Field>"';
notAllowedCharsTextLbl: Label '()[]><|*=', comment = 'DEU="()[]><|*="';

e.g. used in this (incomplete, shorted) code:
local procedure CheckAllowedChars()
    var
        notAllowedCharsVar: Text;
    begin
        notAllowedCharsVar := notAllowedCharsTextLbl;
        for i := 1 to StrLen(notAllowedCharsVar) do
            if StrPos(Usage, Format(notAllowedCharsVar[i])) > 0 then
                Error(notAllowedCharInUsageErr, notAllowedCharsVar[i]);
    end;

Best regards,
Wolfram

**Comment by DanielNT** [comment]
Hi @wansinby, thank you for your comments.

 In your example, the labels 
 
 ```al
OptionTemplateLbl: Label '%2', Comment = 'DEU="%2"';
```
and

```al
notAllowedCharsTextLbl: Label '()[]><|=', comment = 'DEU="()[]><|="';
```

Maybe you could replace these with:

```al
OptionTemplateLbl: Label '%2',  Locked = true;
notAllowedCharsTextLbl: Label '()[]><|=', Locked = true;
```

Are the translation in these two cases language-dependent?

**Comment by DanielNT** [comment]
@wansinby I detected the source of your problem, the setting "Regex for comment" applied believes that you're writing a  comment badly formatted, so it throws an error.

You can use this regex in the setting **Al Translation Center › General: Regex For Comment**
```
[A-Za-z][A-Za-z][A-Za-z]=(?:")
```
instead of default value ```\D\D\D=(?:")```, and test it.

**Comment by wansinby** [comment]
Dear @DanielNT ,
thank you for your fast response. I completly forgot the "Locked"-Instruction, thank you for the reminder. That's the correct way at my code, and everything works fine as expected. I also tested the other solution "[A-Za-z][A-Za-z][A-Za-z]=(?:")" with a comment with translation, and it also works fine.
So I will close this issue.
(Great work!)
