### ISSUE TITLE
Show the reason for error message "Language not mapped %1"

### ISSUE THREAD

**Issue by wansinby** [DanielNT/ALTranslationCenter#7]
Dear Daniel,

I try to make all translations in my AL-extension clean, and your check in "AL Translation Center" showed me many wrong formated translations I was able to fix (Command ATC: Generate Xliff translations from source). I use the setting "Throw Error If Comment Language Not Mapped" set to "Skip all", and I got no errors.

Then I set the setting to "Skip only % prefix", and fixed all new errors - ok. The error messages showed the bad comment so it was easy to find them.

But now, if I set the setting to "Skip none" I get an error "Found language not mapped: "%1". ", and I can't find the reason for this. Searching for "%1% doesn't help, also searching for "comment = "%1  " didn't help.

Is it possible to show the complete line of the xlf-file or the complete comment where your code throws this error, so I can search my code for this piece of code?

Best regards, Wolfram

**Comment by DanielNT** [comment]
Hi @wansinby, great idea. New version **2.3.1** is now available in marketplace with search of occurrence of the source comment.

**Comment by wansinby** [comment]
Dear Daniel,
thank you very much for this really fast response and enhancement. I got the update (before I had a look into my mails) and I got the new errormessage. Great! Now I know which code your check doesn't like:

`UpdateQst: Label 'Update %1?', Comment = '%1="the field caption",DEU="Aktualisiere %1?"';`

How do I have to write this code to be correct for AL (%1 must be explained) and for AL Translation Center with setting "Skip none"?
Best regards, Wolfram

**Comment by DanielNT** [comment]
> Dear Daniel, thank you very much for this really fast response and enhancement. I got the update (before I had a look into my mails) and I got the new errormessage. Great! Now I know which code your check doesn't like:
> 
> `UpdateQst: Label 'Update %1?', Comment = '%1="the field caption",DEU="Aktualisiere %1?"';`
> 
> How do I have to write this code to be correct for AL (%1 must be explained) and for AL Translation Center with setting "Skip none"? Best regards, Wolfram

`Skip none` is the more restrictive option. With this option selected, all %1 or similar comments like the `UpdateQst` label will throw an error. Only language comments are allowed.

`Skip all` is the default value, and simply will ignore if the language is not mapped (was the default behavior before the setting was created, so is selected for compatibility).

`Skip only % preffix` maybe is the value that you want, it won't throw error with format as `UpdateQst`.  In the next example is an invented language prefix `XXX`:

`Skip none` =>                `'XXX="[...]" `=> ERROR              &emsp; &emsp;&emsp;   `'%1"="[...]"`=> ERROR
`Skip only % preffix` => `'XXX="[...]" `=> ERROR                  &emsp;&emsp;&emsp;  `'%1"="[...]"` => OK
`Skip all` =>                    `'XXX="[...]"` => OK                      &emsp; &emsp;&emsp;   `'%1"="[...]"` => OK

**Comment by wansinby** [comment]
Dear Daniel,
thank you for the explanation. So I will use "Skip only % prefix".
Issue is closed.
Best regards, Wolfram
