### ISSUE TITLE
Set Default Language per Extension Setting

### ISSUE THREAD

**Issue by wansinby** [DanielNT/ALTranslationCenter#8]
Dear Daniel,

I tried to enhance the old extension "AL Language Tool" before I found your great improvements. One of the things I tried was to set the default language in the snippets by a setting in the extension settings, and I got it to work. Do you think you could improve your snippets with some features like:
- set default language in extension settings
- make it possible to remove the language from the TAB-list/shortcuts (because the language is set by default language)

Here is my code-example for a snippet with variable content (danm, markdown kills the code, I attach it as a file):

export function tcaptionWithComment() {
    vscode.languages.registerCompletionItemProvider('al', {
        provideCompletionItems(doc, pos, token, context) {
            var defaultLanguage = vscode.workspace.getConfiguration('al-myvscextension').get("defaultLanguage", "DEU");
            var defaultLanguageInShortcut = vscode.workspace.getConfiguration('al-myvscextension').get("defaultLanguageInShortcut", "false");
            var captionString = `Caption = '\${1:EnglishText}', Comment = '`;
            var shortcutcounter = 2; // the next shortcut
            if (defaultLanguageInShortcut) {
                captionString = captionString + `\${${shortcutcounter}:${defaultLanguage}}`;
                shortcutcounter = shortcutcounter + 1;
            } else {
                captionString = captionString + `${defaultLanguage}`;
            }
            captionString = captionString + `=\"\${${shortcutcounter}:YourLanguageText}\"';$0`;
            shortcutcounter += 1; // not used now, but count up if used later
            return [
                {
                    label: "tcaptionWithComment (AL MyVSCExt)",
                    insertText: new vscode.SnippetString(captionString),
                    detail: "UI Texts: Caption with comment (AL MyVSCExt)",
                    kind: vscode.CompletionItemKind.Snippet,
                },
            ];
        }
    });
}

(Please excuse if the code is bad, this is my first time I tried to code in Javascript/Typescript)

Best regards, Wolfram
[AL Snippet with variable content.txt](https://github.com/DanielNT/ALTranslationCenter/files/12111538/AL.Snippet.with.variable.content.txt)

**Comment by DanielNT** [comment]
Hi @wansinby interesting feature and not too difficult to add. I will consider it for adding in next versions.

**Comment by DanielNT** [comment]
@wansinby I have published a new extension based in your suggestions. It is a preview version, try it and give me feedback.

[AL Translation Snippets](https://marketplace.visualstudio.com/items?itemName=daniel-nt.al-translation-snippets)

**Comment by wansinby** [comment]
Dear Daniel,
great new extension, works as expected.
I will use it now (even it is marked as preview).
Best regards, Wolfram
